version: "3.9"

services:
  database:
    container_name: tcc-bd-postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=tcc
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=prisma-postgres
